#!/bin/bash
PROJECT_NAME=""
PROJECT_FILE="/home/git/.git/"
BACKUP_FILE="/home/ftproot/backup/gitbak/"
CURRENT_TIME=`date +%Y%m%d%H%M%S`
tar -czf ${BACKUP_FILE}/${PROJECT_NAME}_${CURRENT_TIME}.tar.gz ${PROJECT_FILE}
file_list=`ls ${BACKUP_FILE} | sort -r`
i=0
for file in $file_list
do
    if (( 5 <= i++ ))
    then
        rm -f ${BACKUP_FILE}${file}
    fi
done
