#!/bin/bash
. iconfig

cd ${temp_dir}

if [ ! -d ${httpd_v} ]; then
    tar xjf ${httpd_v}.tar.bz2
    tar xjf ${apr_v}.tar.bz2
    tar xjf ${apr_util_v}.tar.bz2
    mv ${apr_v} ${httpd_v}/srclib/apr
    mv ${apr_util_v} ${httpd_v}/srclib/apr-util
fi

#install apache
cd ${httpd_v} && \
./configure --prefix=${lanmp_dir}/httpd \
    --enable-load-all-modules \
    --with-pcre=${lanmp_dir}/pcre/bin/pcre-config && \
make && \
make install