#!/bin/bash
temp_dir=temp
lanmp_dir=/lanmp
lanmp_user=lanmp
#run 'ip addr'
net_dev=ens33

#pcre
pcre_v=pcre-8.40

#httpd
httpd_v=httpd-2.4.26
apr_v=apr-1.6.2
apr_util_v=apr-util-1.6.0

#nginx
nginx_v=nginx-1.13.2
pcre_v=pcre-8.40

#php
php_l="php-5.6.30 php-7.1.6"

#mariadb
mariadb_v=mariadb-10.2.6


#initialize
if [ ! -d ${lanmp_dir} ]; then
    mkdir ${lanmp_dir}
fi