#!/bin/bash
. iconfig

#off selinux
setenforce 0
sed -i s/SELINUX=enforcing/SELINUX=disabled/g /etc/selinux/config

#off firewalld
systemctl stop firewalld
systemctl disable firewalld

#add system user
useradd ${lanmp_user} -M -d ${lanmp_dir} -p ${lanmp_user}
cp /etc/skel/.bash* ${lanmp_dir}

#run samba
systemctl start smb
systemctl enable smb

#cp config file
cp ${lanmp_dir}/httpd/conf/httpd.conf ${lanmp_dir}/httpd/conf/httpd.conf.bak
cp -f idefconfig/httpd.conf ${lanmp_dir}/httpd/conf/httpd.conf
cp ${lanmp_dir}/nginx/conf/nginx.conf ${lanmp_dir}/nginx/conf/nginx.conf.bak
cp -f idefconfig/nginx.conf ${lanmp_dir}/nginx/conf/nginx.conf
cp -r idefconfig/htdocs ${lanmp_dir}/httpd/
for php_v in ${php_l}
do
	cp -f idefconfig/${php_v}.ini ${lanmp_dir}/${php_v}/lib/
done

#chown lanmp
chown ${lanmp_user}:${lanmp_user} -R ${lanmp_dir}

#add samba user
smbpasswd -a ${lanmp_user}
