#!/bin/bash
#yum install -y libxml2-devel ncurses-devel openssl-devel gcc-c++ cmake bison java

lanmp_dir=/lanmp
mariadb_v=mariadb-10.1.19
if [ ! -d ${mariadb_v} ]; then
	tar xzf ${mariadb_v}.tar.gz
fi
cd ${mariadb_v} && \
make clean && \
rm -f CMakeCache.txt && \
mkdir ${lanmp_dir}/data
cmake . -DCMAKE_INSTALL_PREFIX=${lanmp_dir}/mariadb \
        -DWITH_INNOBASE_STORAGE_ENGINE=1 \
        -DWITH_ARCHIVE_STORAGE_ENGINE=1 \
        -DWITH_BLACKHOLE_STORAGE_ENGINE=1 \
        -DWITH_READLINE=1 -DWITH_SSL=system \
        -DWITH_ZLIB=system \
        -DWITH_LIBWRAP=0 \
        -DMYSQL_UNIX_ADDR=/tmp/mysql.sock \
        -DDEFAULT_CHARSET=utf8 \
        -DDEFAULT_COLLATION=utf8_general_ci && \
make && make install
