#!/bin/bash
. iconfig

cd ${temp_dir}

if [ ! -d ${mariadb_v} ]; then
    tar xzf ${mariadb_v}.tar.gz
fi
cd ${mariadb_v} && \
rm -f CMakeCache.txt && \
cmake . -DCMAKE_INSTALL_PREFIX=${lanmp_dir}/mariadb \
        -DWITH_INNOBASE_STORAGE_ENGINE=1 \
        -DWITH_ARCHIVE_STORAGE_ENGINE=1 \
        -DWITH_BLACKHOLE_STORAGE_ENGINE=1 \
        -DWITH_READLINE=1 -DWITH_SSL=system \
        -DWITH_ZLIB=system \
        -DWITH_LIBWRAP=0 \
        -DMYSQL_UNIX_ADDR=/tmp/mysql.sock \
        -DDEFAULT_CHARSET=utf8 \
        -DDEFAULT_COLLATION=utf8_general_ci && \
make && make install && \
${lanmp_dir}/mariadb/scripts/mysql_install_db --datadir=${lanmp_dir}/mariadb/data/