#!/bin/bash
. iconfig

cd ${temp_dir}

for php_v in ${php_l}
do
    if [ ! -d ${php_v} ]; then
        tar xjf ${php_v}.tar.bz2
    fi
    cd ${php_v} && \
    ./configure --prefix=${lanmp_dir}/${php_v} \
        --with-openssl=shared \
        --with-zlib=shared \
        --with-bz2=shared \
        --with-curl=shared \
        --with-mysql=shared \
        --with-mysqli=shared \
        --with-pdo-mysql=shared \
        --with-gd=shared \
        --enable-fpm \
        --enable-zip \
        --enable-sockets \
        --enable-mbstring && \
    make && \
    make install && \
    cp php.ini-development ${lanmp_dir}/${php_v}/lib/php.ini && \
    cd -
done