#!/bin/bash
. iconfig

cd ${temp_dir}

for php_v in ${php_l}
do
    if [ ! -d ${php_v} ]; then
        tar xjf ${php_v}.tar.bz2
    fi
    cd ${php_v} && \
    ./configure --prefix=${lanmp_dir}/${php_v} \
    --with-openssl \
    --with-pdo-mysql \
    --with-mysqli \
    --with-gd \
    --with-curl \
    --enable-mbstring && \
    make && \
    make install && \
    cp php.ini-development ${lanmp_dir}/${php_v}/lib/php.ini && \
    cd -
done
