#!/bin/bash
. iconfig
    
#start
function start(){
    ${lanmp_dir}/httpd/bin/httpd -k start
    ${lanmp_dir}/nginx/sbin/nginx
    ${lanmp_dir}/mariadb/bin/mysqld --user=lanmp --datadir=/lanmp/mariadb/data/ --socket=/tmp/mysql.sock > /dev/null &
}
#stop
function stop(){
    ${lanmp_dir}/httpd/bin/httpd -k stop
    ${lanmp_dir}/nginx/sbin/nginx -s stop
    ${lanmp_dir}/mariadb/bin/mysqladmin shutdown
}

#restart
function restart(){
    stop && start
}

if [ ! $1 ] ; then
    echo 'lanmpctl start|stop|restart'
fi

case $1 in
    'start')
        start
        echo 'start'
    ;;
    'stop')
        stop
        echo 'stop'
    ;;
    'restart')
        restart
        echo 'restart'
    ;;
esac
    